### ISSUE TITLE
Harden the server

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/statedecoded#14]
- change passwords
- password protect admin

**Comment by waldoj** [comment]
You should also [password-protect the Solr admin page](http://www.shayanderson.com/linux/how-to-password-protect-apache-solr-server-admin-pages.htm), if you haven't already. It's weird that Solr doesn't do that out of the box. :-/

**Comment by aramonc** [comment]
@ErnieAtLYD @waldoj a little better protection for the solr admin & any other admin tools is IP whitelist. 

We we used to do at ServerGrove was only allow things like that to be accessed from 127.0.0.1 & then you would have to create an SSH tunnel to access the page. It's a bit of a pain to setup & get working, but it's the most secure setup. Apache password protection is prone to brute force attacks.

**Comment by waldoj** [comment]
Hey, do it however you like, but just don't leave it open. :)

**Comment by antoniorllanos** [comment]
statedecoded/admin now protected

**Comment by antoniorllanos** [comment]
solr protected

**Comment by antoniorllanos** [comment]
I also fixed the ports to only allow solr and HTTP access to box
