### ISSUE TITLE
Use the latest version of The State Decoded

### ISSUE THREAD

**Issue by waldoj** [CodeforSouth/statedecoded#3]
The version here is pretty old. [Merge in v0.81](https://github.com/statedecoded/statedecoded/releases/tag/v0.81) to see some enormous improvements.

**Comment by ErnieAtLYD** [comment]
Thanks, Waldo. Levi, can I assign this to you?

**Comment by niterain** [comment]
sure

**Comment by mfliegel** [comment]
Hi Waldo,

I'm new with Code for Miami and trying to re-start this - Adrian gave me the team / repo access last night.  I'm new to Github so please excuse my ignorance.  I mentioned to Ernie and Adrian yesterday that their repo was really out of date.  They said to Fork another copy and request a pull -- they are concerned about losing any customization.  However the only Commit I see from our side (Rebekah) is a folder of Miami-Dade XML.  Then as I was going through the site tonight I see this Issue where you already suggest doing a merge.  If I execute the merge will the one folder of XML be preserved?  What are the steps to do this?

Thanks,
Marvin

**Comment by waldoj** [comment]
Nothing appears to have been changed. The config file hasn't been created (`/includes/config.inc.php`), and the custom functions file hasn't been created (`includes/class.Miami.inc.php`). It sure looks like all that's been done is `/MIA_municode_files/` was added. I suspect you could blow away everything else, replace it with the current version, and you'd be right back where you are now. :)

**Comment by mfliegel** [comment]
Thanks for taking a close look into the files, Waldo.

Adrian or Ernie, please give me you blessing for this approach!

**Comment by aramonc** [comment]
@mfliegel so long as you don't delete the folder with the XML while replacing everything else, it should be fine.

**Comment by ErnieAtLYD** [comment]
Antonio created a new AWS instance on http://54.88.152.46 which now has the newest version of TheStateDecoded.
