### ISSUE TITLE
Write an XSLT to transform Municode -> State Decoded

### ISSUE THREAD

**Issue by waldoj** [CodeforSouth/statedecoded#4]
It's probably best to map Municode's XML to The State Decoded's (very simple) XML format with XSLT. [A sample Florida Statutes -> State Decoded XSLT is included with The State Decoded](https://github.com/Code-for-Miami/statedecoded/blob/master/sample.xsl), so that's probably a good place to get started. It's very well commented.

At present, this XSLT stands to be a Very Big Deal outside of Miami. We'd package it with The State Decoded, making it trivial to stand up a State Decoded site for any legal code housed by Municode. No XSLT or converters required—it'd basically be turnkey.

**Comment by ErnieAtLYD** [comment]
@kempchee created a rails script that parsed the Municode XML into a StateDecoded format. He ended up posting the result XML code to this repo: https://github.com/kempchee/miami-dade-statedecoded-xml
