### ISSUE TITLE
miamicode.org Domain?

### ISSUE THREAD

**Issue by aramonc** [CodeforSouth/statedecoded#7]
We have the miamicode.org domain on the ServerGrove server. Since the states decoded project is on another server, should we point the domain to that?

**Comment by ErnieAtLYD** [comment]
Hey, so I never responded to this but my gut instinct says no BECAUSE on conversations with State Decoded, folks wanted to emphasize that this was the legal code for Miami-Dade County and NOT Miami, the city. So the less ambiguous about this, the better.
