### ISSUE TITLE
Investigate why search isn't working

### ISSUE THREAD

**Issue by ErnieAtLYD** [CodeforSouth/statedecoded#8]
Per @antoniorllanos: "I think we need to understand the inputs and the outputs and the proper mapping.  I was reviewing everything last night and noticed some bugs in the ruby code that I resolved with respect to filenames and special characters within the XML.  When I imported into Solr, it failed, and in looking at the XML doc, it seems the Ruby parser is adding the title to the section, creating content on the site that contains the title within it.  However, Bill Hunt told me that the xml is fine, so the Solr issue is somewhere else.  I am going to try a reimport with a Solr throttle of 1 to see which file fails to determine the root cause."

**Comment by ErnieAtLYD** [comment]
@antoniorllanos figured out that a solr rollback to 4.3.1 was necessary. Antonio, does this need to be reflected in the statedecoded docs somewhere?

**Comment by waldoj** [comment]
Antonio opened an issue on the State Decoded repository, and we'll sort that out!
